### PR TITLE
feat(server-routes): json-editor for tab inputs

### PR DESCRIPTION
**Pull request by arashsheyda**
ability to write json and have type option in inputs,
(I think still there is some bugs when you switch from json to input, the change type might not work accurately in some caces)

https://github.com/nuxt/devtools/assets/38922203/e0e523df-2607-41af-866a-8246e21d0a21

### CODE REVIEW

**Comment by antfu** [comment]
From the from to object, it becomes 

```json
[
  {
    "key": "foo",
    "value": "bar"
  }
]
```

instead of 

```json
{
  "foo": "bar"
}
```

Does not sounds ideal to me. Maybe we could just not syncing them?

**Comment by arashsheyda** [comment]
@antfu Awww that's so right, I totally miss it, thanks

yes I think it would be easy if we don't sync them, and do you think we need json-editor only for body tab or all the tabs?

**Comment by antfu** [comment]
I think only for body should be good enough

**Comment by arashsheyda** [comment]
here is the latest

https://github.com/nuxt/devtools/assets/38922203/f0d475cc-0405-4229-918a-2e23fab660e0

**Pull request merged**
