### PR TITLE
feat: init server routes tab

### LINKED ISSUE #110: API Routes Tab
Provide a tab for displaying API routes from Nitro, and a playground to send request

### PR DESCRIPTION
**Pull request by arashsheyda**
tried to help with 1463495118 tree view.

Resolves #110

### CODE REVIEW

**Comment by arashsheyda** [comment]
add experimental server routes [110](https://github.com/nuxt/devtools/issues/110)

**Comment by antfu** [comment]
Can you separate them into two PRs?

**Comment by Atinux** [comment]
Happy to share a screenshot on how it looks like?

**Comment by arashsheyda** [comment]
@Atinux sure, here is a [video](https://res.cloudinary.com/arashsheyda/video/upload/v1680804471/nuxt/devtool-server-rotues_ydutr2.mp4) and a [screenshot](https://res.cloudinary.com/arashsheyda/image/upload/v1680804496/nuxt/devtool-server-routes_ayfgib.png)

**Comment by Atinux** [comment]
Wow it looks very nice @arashsheyda ! Thank you for working on it!

I think @antfu will do some UI/UX cleanup before and review once he got time :)

**Comment by arashsheyda** [comment]
thank you @Atinux, I'm glad to help.
Thanks again

**Comment by antfu** [comment]
Thanks a lot for the initiative! I think there are some details we still need to take care about. I refactored them a bit and left some todos, feel free to work on them if you want, or I will take my time to improve them slowly.

**Comment by arashsheyda** [comment]
@antfu thank you, i try to help,
thanks for the opportunity

**Pull request merged**
