### PR TITLE
feat: minimize panel on inactive

### PR DESCRIPTION
**Pull request by antfu**
I found that, sometimes, the floating panel took a bit too much space from the app. So I am thinking of having a way to minimize it when not in use for a while.

The effect looks like this (shorten the timeout to 2s for demo):

https://github.com/nuxt/devtools/assets/11247099/4cbafb99-0f92-4666-bd4c-8064db0e78cf

I'd like to hear your opinion on this, and if we should make it configurable?

### CODE REVIEW

**Comment by webfansplz** [comment]
I thought about it, too. My idea is that we can output a open DevTools tip in the project's terminal, and when the user clicks on it, we can trigger the DevTools to open in the page. We need a configuration to allow users to toggle between these two options.

**Comment by webfansplz** [comment]
> I thought about it, too. My idea is that we can output a open DevTools tip in the project's terminal, and when the user clicks on it, we can trigger the DevTools to open in the page. We need a configuration to allow users to toggle between these two options.

Additionally, regarding the `minimize` option, I think it makes sense. Completely hiding it might be necessary for some users.

**Comment by antfu** [comment]
@webfansplz I was thinking about doing it shortcut-only as well. It might be an option, but in that case, we also need to find a way to trigger it on touch devices.

**Comment by webfansplz** [comment]
Awesome work 🤩. I’ll port it to the Vue DevTools🤓

**Pull request merged**
