### PR TITLE
feat: add Unix os support to the `Build Analyze` integration

### PR DESCRIPTION
**Pull request by Dev1436**
Hi,

I extended the OS support for the `Build Analyze` feature to:
* SunOS
* AIX
* OpenBSD
* FreeBSD
* NetBSD

Also removed the unused dependency on `fast-folder-size`. First ever PR for me, wasn't sure about dependency etiquette, so if it should have been done by the core team, please let me know so I don't make that mistake next time.

Thanks

### CODE REVIEW

**Comment by antfu** [comment]
I am not very confident about taking those complexities. Possible to push those changes to upstream `fast-folder-size`, or create another package so we could use it?

**Comment by Dev1436** [comment]
ok, let me see what I can do.

Thanks for taking a look.

**Comment by Dev1436** [comment]
Sooo, I did not know pushing to my branch would do all this here.

Sorry bout that.

While I was looking into setting up a vagrant/qemu setup for AIX, it dawned on me that it's significantly easier to just use the built in node fs api. So thats what I did, let me know if there are any concerns with this approach.

Thanks again for your time and all the awesome work y'all are doing!

**Comment by antfu** [comment]
We have end up with #409, and I hope it would works better across platforms. Feel free to open another PR if you see any other improvements. Thanks

**Pull request closed without merging**
